### ISSUE TITLE
Problem with Scenario Outline

### ISSUE THREAD

**Issue by miiimooo** [allure-framework/allure-behat#8]
It seems that when a Scenario **Outline** fails something goes wrong. I have a test like this

```
Feature: Hero
  Scenario Outline: Create hero.
    Given I am on "<url>"
    Then I fill in the following:
      | Titel    | YYZ H1 |
      | Subtitle | Yyz H2 |
    Then I press the "Spara" button
    Then I should see the success message "YYZ H1 (<type>) har skapats."
 
    Examples:
      | type         | url                    |
      | Article      | /node/add/article      |

```

When it fails I get this in Allure:

```
Error: Call to a member function getMessage() on null in /drone/src/vendor/wklive/allure-behat3/src/WKLive/Behat/Formatter/BehatAllureFormatter.php on line 460 #0 /drone/src/vendor/wklive/allure-behat3/src/WKLive/Behat/Formatter/BehatAllureFormatter.php(378): WKLive\Behat\Formatter\BehatAllureFormatter->addTestCaseFailed()
#1 /drone/src/vendor/wklive/allure-behat3/src/WKLive/Behat/Formatter/BehatAllureFormatter.php(271): WKLive\Behat\Formatter\BehatAllureFormatter->processScenarioResult(Object(Behat\Testwork\Tester\Result\TestResults))
#2 [internal function]: WKLive\Behat\Formatter\BehatAllureFormatter->onAfterOutlineTested(Object(Behat\Behat\EventDispatcher\Event\AfterOutlineTested), 'tester.outline_...', Object(Behat\Testwork\EventDispatcher\TestworkEventDispatcher))
#3 /drone/src/vendor/symfony/event-dispatcher/EventDispatcher.php(174): call_user_func(Array, Object(Behat\Behat\EventDispatcher\Event\AfterOutlineTested), 'tester.outline_...', Object(Behat\Testwork\EventDispatcher\TestworkEventDispatcher))
#4 /drone/src/vendor/behat/behat/src/Behat/Testwork/EventDispatcher/TestworkEventDispatcher.php(39): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'tester.outline_...', Object(Behat\Behat\EventDispatcher\Event\AfterOutlineTested))
#5 /drone/src/vendor/behat/behat/src/Behat/Behat/EventDispatcher/Tester/EventDispatchingOutlineTester.php(87): Behat\Testwork\EventDispatcher\TestworkEventDispatcher->dispatch('tester.outline_...', Object(Behat\Behat\EventDispatcher\Event\AfterOutlineTested))
#6 /drone/src/vendor/behat/behat/src/Behat/Behat/Tester/Runtime/RuntimeFeatureTester.php(85): Behat\Behat\EventDispatcher\Tester\EventDispatchingOutlineTester->tearDown(Object(Behat\Behat\Context\Environment\UninitializedContextEnvironment), Object(Behat\Gherkin\Node\FeatureNode), Object(Behat\Gherkin\Node\OutlineNode), false, Object(Behat\Testwork\Tester\Result\TestResults))
#7 /drone/src/vendor/behat/behat/src/Behat/Behat/Hook/Tester/HookableFeatureTester.php(72): Behat\Behat\Tester\Runtime\RuntimeFeatureTester->test(Object(Behat\Behat\Context\Environment\UninitializedContextEnvironment), Object(Behat\Gherkin\Node\FeatureNode), false)
#8 /drone/src/vendor/behat/behat/src/Behat/Behat/EventDispatcher/Tester/EventDispatchingFeatureTester.php(71): Behat\Behat\Hook\Tester\HookableFeatureTester->test(Object(Behat\Behat\Context\Environment\UninitializedContextEnvironment), Object(Behat\Gherkin\Node\FeatureNode), false)
#9 /drone/src/vendor/behat/behat/src/Behat/Testwork/Tester/Runtime/RuntimeSuiteTester.php(63): Behat\Behat\EventDispatcher\Tester\EventDispatchingFeatureTester->test(Object(Behat\Behat\Context\Environment\UninitializedContextEnvironment), Object(Behat\Gherkin\Node\FeatureNode), false)
#10 /drone/src/vendor/behat/behat/src/Behat/Testwork/Hook/Tester/HookableSuiteTester.php(73): Behat\Testwork\Tester\Runtime\RuntimeSuiteTester->test(Object(Behat\Behat\Context\Environment\UninitializedContextEnvironment), Object(Behat\Testwork\Specification\GroupedSpecificationIterator), false)
#11 /drone/src/vendor/behat/behat/src/Behat/Testwork/EventDispatcher/Tester/EventDispatchingSuiteTester.php(72): Behat\Testwork\Hook\Tester\HookableSuiteTester->test(Object(Behat\Behat\Context\Environment\UninitializedContextEnvironment), Object(Behat\Testwork\Specification\GroupedSpecificationIterator), false)
#12 /drone/src/vendor/behat/behat/src/Behat/Testwork/Tester/Runtime/RuntimeExercise.php(71): Behat\Testwork\EventDispatcher\Tester\EventDispatchingSuiteTester->test(Object(Behat\Behat\Context\Environment\UninitializedContextEnvironment), Object(Behat\Testwork\Specification\GroupedSpecificationIterator), false)
#13 /drone/src/vendor/behat/behat/src/Behat/Testwork/EventDispatcher/Tester/EventDispatchingExercise.php(70): Behat\Testwork\Tester\Runtime\RuntimeExercise->test(Array, false)
#14 /drone/src/vendor/behat/behat/src/Behat/Testwork/Ordering/OrderedExercise.php(80): Behat\Testwork\EventDispatcher\Tester\EventDispatchingExercise->test(Array, false)
#15 /drone/src/vendor/behat/behat/src/Behat/Testwork/Tester/Cli/ExerciseController.php(149): Behat\Testwork\Ordering\OrderedExercise->test(Array, false)
#16 /drone/src/vendor/behat/behat/src/Behat/Testwork/Tester/Cli/ExerciseController.php(108): Behat\Testwork\Tester\Cli\ExerciseController->testSpecifications(Object(Symfony\Component\Console\Input\ArgvInput), Array)
#17 /drone/src/vendor/behat/behat/src/Behat/Testwork/Cli/Command.php(63): Behat\Testwork\Tester\Cli\ExerciseController->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#18 /drone/src/vendor/symfony/console/Command/Command.php(264): Behat\Testwork\Cli\Command->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#19 /drone/src/vendor/symfony/console/Application.php(841): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#20 /drone/src/vendor/symfony/console/Application.php(206): Symfony\Component\Console\Application->doRunCommand(Object(Behat\Testwork\Cli\Command), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#21 /drone/src/vendor/behat/behat/src/Behat/Testwork/Cli/Application.php(124): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#22 /drone/src/vendor/symfony/console/Application.php(125): Behat\Testwork\Cli\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#23 /drone/src/vendor/behat/behat/bin/behat(34): Symfony\Component\Console\Application->run()
#24 {main}
Error: Call to a member function getMessage() on null in WKLive\Behat\Formatter\BehatAllureFormatter->addTestCaseFailed() (line 460 of /drone/src/vendor/wklive/allure-behat3/src/WKLive/Behat/Formatter/BehatAllureFormatter.php).
```

**Comment by eduard-sukharev** [comment]
Your error has nthing to do with this repo and this code. Here is not the right place to post a message to ask for help with your implementation, better try on [gitter](https://gitter.im/allure-framework/allure-core).

Regaring your issue, though, it's clear that you have no `$this-exception` set, which means you expected it to be set on some other event callback, which didn't happen, apparently. Try to debug and see when and in which order which of the events are called.
